---
title: Summary figures
output: html_document
---

sgRNA-level Area Under ROC and Area Under Precision-Recall Curves across cell lines

```{r}
library(tidyverse)

sgRNA_level_tot <- read_tsv('results/sgRNA_level_metrics.tsv', col_types = cols())

ggplot(sgRNA_level_tot, aes(x = cell_line, y = AUC, fill = metric)) +
  geom_bar(stat='identity', position = 'dodge', color = NA) +
  theme_bw() +
  labs(x = 'Cell line', y = 'AUROC/AUPrR', fill = 'Metric', title = 'sgRNA-level metrics') +
    theme(plot.title = element_text(hjust = 0.5, size = 16), panel.border = element_blank(), 
    panel.grid.major = element_blank(), panel.grid.minor = element_blank(), 
    aspect.ratio = 1,
    axis.line = element_line(colour = "black"),
    axis.text = element_text(size = 12, colour = "black"),
    axis.text.x = element_text(angle = 45, hjust = 1),
    axis.title = element_text(size = 14),
    legend.text = element_text(size = 12),
    legend.title = element_text(size = 14))
```

sgRNA-level Recall at 5% False Discovery Rate

```{r}
sgRNA_level_ROC_tot <- read_tsv('results/sgRNA_level_recall.tsv', col_types = cols())

ggplot(sgRNA_level_ROC_tot, aes(x = cell_line, y = Recall)) +
  geom_bar(stat='identity', position = 'dodge', color = NA, fill = 'lightblue') +
  theme_bw() +
  labs(x = 'Cell line', y = 'Recall at 5% FDR', title = 'sgRNA-level recall') +
    theme(plot.title = element_text(hjust = 0.5, size = 16), panel.border = element_blank(), 
    panel.grid.major = element_blank(), panel.grid.minor = element_blank(), 
    aspect.ratio = 1,
    axis.line = element_line(colour = "black"),
    axis.text = element_text(size = 12, colour = "black"),
    axis.text.x = element_text(angle = 45, hjust = 1),
    axis.title = element_text(size = 14),
    legend.text = element_text(size = 12),
    legend.title = element_text(size = 14))
```

Gene-level Area Under ROC and Area Under Precision-Recall Curves across cell lines

```{r}
gene_level_tot <- read_tsv('results/gene_level_metrics.tsv', col_types = cols())

ggplot(gene_level_tot, aes(x = cell_line, y = AUC, fill = metric)) +
  geom_bar(stat='identity', position = 'dodge', color = NA) +
  theme_bw() +
  labs(x = 'Cell line', y = 'AUROC/AUPrR', fill = 'Metric', title = 'Gene-level metrics') +
    theme(plot.title = element_text(hjust = 0.5, size = 16), panel.border = element_blank(), 
    panel.grid.major = element_blank(), panel.grid.minor = element_blank(), 
    aspect.ratio = 1,
    axis.line = element_line(colour = "black"),
    axis.text = element_text(size = 12, colour = "black"),
    axis.text.x = element_text(angle = 45, hjust = 1),
    axis.title = element_text(size = 14),
    legend.text = element_text(size = 12),
    legend.title = element_text(size = 14))
```

Gene-level Recall at 5% False Discovery Rate

```{r}
gene_level_ROC_tot <- read_tsv('results/gene_level_recall.tsv', col_types = cols())

ggplot(gene_level_ROC_tot, aes(x = cell_line, y = Recall)) +
  geom_bar(stat='identity', position = 'dodge', color = NA, fill = 'lightblue') +
  theme_bw() +
  labs(x = 'Cell line', y = 'Recall at 5% FDR', title = 'Gene-level recall') +
    theme(plot.title = element_text(hjust = 0.5, size = 16), panel.border = element_blank(), 
    panel.grid.major = element_blank(), panel.grid.minor = element_blank(), 
    aspect.ratio = 1,
    axis.line = element_line(colour = "black"),
    axis.text = element_text(size = 12, colour = "black"),
    axis.text.x = element_text(angle = 45, hjust = 1),
    axis.title = element_text(size = 14),
    legend.text = element_text(size = 12),
    legend.title = element_text(size = 14))
```

Recall at 5% False Discovery Rate across gene signatures

```{r}
gene_signatures_tot <- read_tsv('results/gene_signatures.tsv', col_types = cols())

ggplot(gene_signatures_tot, aes(x = metric, y = Recall, fill = cell_line)) +
  geom_bar(stat='identity', position = 'dodge', color = NA) +
  theme_bw() +
  labs(x = 'Gene signature', y = 'Recall at 5% FDR', fill = 'Cell line') +
    theme(plot.title = element_text(hjust = 0.5, size = 16), panel.border = element_blank(), 
    panel.grid.major = element_blank(), panel.grid.minor = element_blank(), 
    aspect.ratio = 1,
    axis.line = element_line(colour = "black"),
    axis.text = element_text(size = 12, colour = "black"),
    axis.text.x = element_text(angle = 45, hjust = 1),
    axis.title = element_text(size = 14),
    legend.text = element_text(size = 12),
    legend.title = element_text(size = 14)) +
    scale_fill_brewer(palette = 'Paired')
```

